# Generated by Django 2.1.7 on 2019-09-12 06:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20190904_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AlterField(
            model_name='datastudent',
            name='Guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian', to='accounts.Guardian'),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 6, 19, 9, 875841, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
