# Generated by Django 2.1.7 on 2019-09-12 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20190912_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 8, 40, 22, 625133, tzinfo=utc)),
        ),
    ]
