# Generated by Django 2.1.7 on 2019-09-16 11:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20190916_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastudent',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 11, 51, 46, 298854, tzinfo=utc)),
        ),
    ]
