# Generated by Django 2.1.7 on 2019-09-20 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190919_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('National_ID', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=130)),
                ('Phone', models.CharField(max_length=150)),
                ('Gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=130)),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=130)),
                ('Religion', models.CharField(choices=[('moslem', 'moslem'), ('Christian', 'Christian'), ('Others', 'Others')], max_length=130)),
                ('Birth_Date', models.CharField(max_length=100)),
                ('Present_Address', models.CharField(max_length=100)),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Salary_Type', models.CharField(choices=[('Monthly', 'Monthly'), ('hourly', 'hourly')], max_length=130)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarian'), ('Receiptionist', 'Receiptionist'), ('Accountant', 'Accountant'), ('Staff', 'Staff')], max_length=130)),
                ('Joining_Date', models.DateField(default=django.utils.timezone.now, max_length=100)),
                ('Resume', models.ImageField(upload_to='gallery')),
                ('Other_Info', models.TextField(max_length=100)),
                ('Employee_Photo', models.ImageField(upload_to='gallery')),
                ('Salary_Grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.SalaryGrade')),
            ],
        ),
        migrations.DeleteModel(
            name='HumanResource',
        ),
    ]
