# Generated by Django 2.1.7 on 2019-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20190920_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='Enter Pass', max_length=100),
        ),
    ]
