# Generated by Django 2.1.7 on 2019-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Joining_Date',
            field=models.CharField(max_length=100),
        ),
    ]
