# Generated by Django 2.1.7 on 2019-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
