# Generated by Django 2.1.7 on 2019-09-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20190926_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='ClassName',
            field=models.CharField(choices=[('Form_One', 'Form_One'), ('Form_Two', 'Form_Two'), ('Form_Three', 'Form_Three'), ('Form_Four', 'Form_Four'), ('Form_Five_Arts', 'Form_Five_Arts'), ('Form_Five_Sciences', 'Form_Five_Sciences'), ('Form_Five_Six', 'Form_Six_Arts'), ('Form_Six_Sciences', 'Form_Six_Sciences')], default='class Name', max_length=130),
        ),
        migrations.AlterField(
            model_name='datastudent',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.Sectioninformation'),
        ),
        migrations.AlterField(
            model_name='sectioninformation',
            name='NameOfClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='accounts.Classinformation'),
        ),
        migrations.AlterField(
            model_name='sectioninformation',
            name='SectionName',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='section', max_length=130),
        ),
    ]
