# Generated by Django 2.1.7 on 2019-09-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20190927_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='School',
        ),
    ]
