# Generated by Django 2.1.7 on 2019-09-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_remove_feecollection_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='Student_Name',
        ),
    ]
