# Generated by Django 2.1.7 on 2019-09-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190927_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Sectioninformation'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='Student_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.DataStudent'),
        ),
    ]
