# Generated by Django 2.1.7 on 2019-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20190927_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='Class',
            field=models.CharField(default='netr', max_length=130),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='Section',
            field=models.CharField(default='netr', max_length=130),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='Student_Name',
            field=models.CharField(default='netr', max_length=130),
        ),
    ]
