# Generated by Django 2.1.7 on 2019-09-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20190927_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='Student_Name',
        ),
    ]
