# Generated by Django 2.2.4 on 2019-10-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20190928_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('fee_amount', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('month', models.DateField(max_length=100)),
                ('is_discount_applicable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('paid_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=100)),
                ('gross_amount', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=300)),
                ('date', models.DateField(null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Classinformation')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DataStudent')),
            ],
        ),
    ]
